# Generated by Django 6.0.2 on 2026-02-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workspace',
            table='workspaces',
        ),
    ]
