# Generated by Django 6.0.2 on 2026-02-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
